// Code generated by gen_version. DO NOT EDIT.

package thoop

const (
	VersionMajor uint   = 0       // x-release-please-major
	VersionMinor uint   = 1       // x-release-please-minor
	VersionPatch uint   = 9       // x-release-please-patch
	Version      string = "0.1.9" // x-release-please-version
)
