// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlitec

import (
	"context"
	"time"
)

const deleteTokenMetadata = `-- name: DeleteTokenMetadata :exec
DELETE FROM tokens WHERE id = 1
`

func (q *Queries) DeleteTokenMetadata(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTokenMetadata)
	return err
}

const getTokenMetadata = `-- name: GetTokenMetadata :one
SELECT id, token_type, expiry FROM tokens WHERE id = 1
`

func (q *Queries) GetTokenMetadata(ctx context.Context) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenMetadata)
	var i Token
	err := row.Scan(&i.ID, &i.TokenType, &i.Expiry)
	return i, err
}

const upsertTokenMetadata = `-- name: UpsertTokenMetadata :exec
INSERT INTO tokens (id, token_type, expiry)
VALUES (1, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    token_type = excluded.token_type,
    expiry = excluded.expiry
`

type UpsertTokenMetadataParams struct {
	TokenType string    `json:"token_type"`
	Expiry    time.Time `json:"expiry"`
}

func (q *Queries) UpsertTokenMetadata(ctx context.Context, arg UpsertTokenMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertTokenMetadata, arg.TokenType, arg.Expiry)
	return err
}
