// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package sqlitec

import (
	"context"
	"time"
)

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens WHERE id = 1
`

func (q *Queries) DeleteToken(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteToken)
	return err
}

const getToken = `-- name: GetToken :one
SELECT id, access_token, refresh_token, token_type, expiry FROM tokens WHERE id = 1
`

func (q *Queries) GetToken(ctx context.Context) (Token, error) {
	row := q.db.QueryRowContext(ctx, getToken)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.Expiry,
	)
	return i, err
}

const upsertToken = `-- name: UpsertToken :exec
INSERT INTO tokens (id, access_token, refresh_token, token_type, expiry)
VALUES (1, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    access_token = excluded.access_token,
    refresh_token = excluded.refresh_token,
    token_type = excluded.token_type,
    expiry = excluded.expiry
`

type UpsertTokenParams struct {
	AccessToken  string    `json:"access_token"`
	RefreshToken *string   `json:"refresh_token"`
	TokenType    string    `json:"token_type"`
	Expiry       time.Time `json:"expiry"`
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertToken,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenType,
		arg.Expiry,
	)
	return err
}
