//go:build dev

package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	go_json "github.com/goccy/go-json"
)

type semver struct {
	Major uint
	Minor uint
	Patch uint
}

func (s semver) String() string {
	return fmt.Sprintf("%d.%d.%d", s.Major, s.Minor, s.Patch)
}

func (s semver) Snapshot() semver {
	return semver{
		Major: s.Major,
		Minor: s.Minor,
		Patch: s.Patch + 1,
	}
}

func (s semver) SnapshotString() string {
	return s.Snapshot().String() + "-snapshot"
}

type generator struct {
	manifestReader io.Reader
	outputWriter   io.Writer
}

func main() {
	snapshot := flag.Bool("snapshot", false, "generate snapshot version for local dev")
	flag.Parse()

	f, err := os.Open(".release-please-manifest.json")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	out, err := os.Create("version_gen.go")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	g := &generator{
		manifestReader: f,
		outputWriter:   out,
	}

	version, err := g.run(*snapshot)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated version_gen.go: %s\n", version)
}

func (g *generator) run(snapshot bool) (string, error) {
	data, err := io.ReadAll(g.manifestReader)
	if err != nil {
		return "", err
	}

	var manifest map[string]string
	if err := go_json.Unmarshal(data, &manifest); err != nil {
		return "", err
	}

	version := manifest["."]
	content, versionStr, err := generate(version, snapshot)
	if err != nil {
		return "", err
	}

	if _, err := g.outputWriter.Write([]byte(content)); err != nil {
		return "", err
	}

	return versionStr, nil
}

func generate(version string, snapshot bool) (content string, versionStr string, err error) {
	sv, err := parseVersion(version)
	if err != nil {
		return "", "", err
	}

	// If already a snapshot version, don't snapshot again
	isAlreadySnapshot := strings.Contains(version, "-snapshot")
	if snapshot && !isAlreadySnapshot {
		*sv = sv.Snapshot()
		version = sv.String() + "-snapshot"
	} else if isAlreadySnapshot {
		// Keep existing snapshot version as-is
		version = sv.String() + "-snapshot"
	}

	content = fmt.Sprintf(`// Code generated by gen_version. DO NOT EDIT.

package thoop

const (
	VersionMajor uint   = %d        // x-release-please-major
	VersionMinor uint   = %d        // x-release-please-minor
	VersionPatch uint   = %d       // x-release-please-patch
	Version      string = "%s" // x-release-please-version
)
`, sv.Major, sv.Minor, sv.Patch, version)

	return content, version, nil
}

var errInvalidVersion = errors.New("invalid version format")

func parseVersion(v string) (*semver, error) {
	v = strings.TrimPrefix(v, "v")
	if v == "" {
		return nil, errInvalidVersion
	}

	parts := strings.SplitN(v, ".", 3)
	if len(parts) < 3 {
		return nil, errInvalidVersion
	}

	major, err := strconv.ParseUint(parts[0], 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid major version: %w", err)
	}

	minor, err := strconv.ParseUint(parts[1], 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid minor version: %w", err)
	}

	patchStr := strings.SplitN(parts[2], "-", 2)[0]
	patch, err := strconv.ParseUint(patchStr, 10, 32)
	if err != nil {
		return nil, fmt.Errorf("invalid patch version: %w", err)
	}

	return &semver{
		Major: uint(major),
		Minor: uint(minor),
		Patch: uint(patch),
	}, nil
}
