// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Token struct {
	ID           int64     `json:"id"`
	AccessToken  string    `json:"access_token"`
	RefreshToken *string   `json:"refresh_token"`
	TokenType    string    `json:"token_type"`
	Expiry       time.Time `json:"expiry"`
}
