// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteToken(ctx context.Context) error
	GetToken(ctx context.Context) (Token, error)
	UpsertToken(ctx context.Context, arg UpsertTokenParams) error
}

var _ Querier = (*Queries)(nil)
