// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package pgc

import (
	"context"
	"database/sql"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (whoop_user_id, key_hash, name)
VALUES ($1, $2, $3)
RETURNING id, whoop_user_id, key_hash, name, created_at, last_used_at, revoked
`

type CreateAPIKeyParams struct {
	WhoopUserID int64          `json:"whoop_user_id"`
	KeyHash     string         `json:"key_hash"`
	Name        sql.NullString `json:"name"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, createAPIKey, arg.WhoopUserID, arg.KeyHash, arg.Name)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WhoopUserID,
		&i.KeyHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, whoop_user_id, key_hash, name, created_at, last_used_at, revoked FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WhoopUserID,
		&i.KeyHash,
		&i.Name,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Revoked,
	)
	return i, err
}

const getAPIKeysByUser = `-- name: GetAPIKeysByUser :many
SELECT id, whoop_user_id, key_hash, name, created_at, last_used_at, revoked FROM api_keys WHERE whoop_user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAPIKeysByUser(ctx context.Context, whoopUserID int64) ([]ApiKey, error) {
	rows, err := q.db.QueryContext(ctx, getAPIKeysByUser, whoopUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WhoopUserID,
			&i.KeyHash,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Revoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked = true WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, revokeAPIKey, id)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateAPIKeyLastUsed, id)
	return err
}
