// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int64              `json:"id"`
	WhoopUserID int64              `json:"whoop_user_id"`
	KeyHash     string             `json:"key_hash"`
	Name        *string            `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	Revoked     bool               `json:"revoked"`
}

type User struct {
	WhoopUserID int64              `json:"whoop_user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Banned      bool               `json:"banned"`
}

type WebhookEvent struct {
	TraceID        string             `json:"trace_id"`
	ID             *int64             `json:"id"`
	WhoopUserID    int64              `json:"whoop_user_id"`
	Timestamp      pgtype.Timestamptz `json:"timestamp"`
	EntityID       string             `json:"entity_id"`
	EntityType     string             `json:"entity_type"`
	Action         string             `json:"action"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
}
