// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgc

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID          int64          `json:"id"`
	WhoopUserID int64          `json:"whoop_user_id"`
	KeyHash     string         `json:"key_hash"`
	Name        sql.NullString `json:"name"`
	CreatedAt   time.Time      `json:"created_at"`
	LastUsedAt  time.Time      `json:"last_used_at"`
	Revoked     bool           `json:"revoked"`
}

type User struct {
	WhoopUserID int64     `json:"whoop_user_id"`
	CreatedAt   time.Time `json:"created_at"`
	Banned      bool      `json:"banned"`
}
