// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pgc

import (
	"context"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET banned = true WHERE whoop_user_id = $1
`

func (q *Queries) BanUser(ctx context.Context, whoopUserID int64) error {
	_, err := q.db.Exec(ctx, banUser, whoopUserID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (whoop_user_id)
VALUES ($1)
RETURNING whoop_user_id, created_at, banned
`

func (q *Queries) CreateUser(ctx context.Context, whoopUserID int64) (User, error) {
	row := q.db.QueryRow(ctx, createUser, whoopUserID)
	var i User
	err := row.Scan(&i.WhoopUserID, &i.CreatedAt, &i.Banned)
	return i, err
}

const getOrCreateUser = `-- name: GetOrCreateUser :one
INSERT INTO users (whoop_user_id)
VALUES ($1)
ON CONFLICT (whoop_user_id) DO UPDATE SET whoop_user_id = EXCLUDED.whoop_user_id
RETURNING whoop_user_id, created_at, banned
`

func (q *Queries) GetOrCreateUser(ctx context.Context, whoopUserID int64) (User, error) {
	row := q.db.QueryRow(ctx, getOrCreateUser, whoopUserID)
	var i User
	err := row.Scan(&i.WhoopUserID, &i.CreatedAt, &i.Banned)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT whoop_user_id, created_at, banned FROM users WHERE whoop_user_id = $1
`

func (q *Queries) GetUser(ctx context.Context, whoopUserID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, whoopUserID)
	var i User
	err := row.Scan(&i.WhoopUserID, &i.CreatedAt, &i.Banned)
	return i, err
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users SET banned = false WHERE whoop_user_id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, whoopUserID int64) error {
	_, err := q.db.Exec(ctx, unbanUser, whoopUserID)
	return err
}
